eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411
server:
  port: 8090
spring:

  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/v1/order/**
          filters:
#            - AddResponseHeader=X-Response-Default-Red, KETMON-ESHMAT4444444
            - AddRequestHeader=X-Request-Default-Red, KETMON-ESHMAT
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**


    compatibility-verifier:
      enabled: false
  sleuth:
    propagation:
      type: w3c,b3
    supportsJoin: false
    traceId128: true
  zipkin:
    base-url: http://localhost:9411
